name: LandClaimPlugin
version: '2.0.0'
main: org.ayosynk.landClaimPlugin.LandClaimPlugin
api-version: '1.21'
author: AyoSynk
soft-depend: [WorldGuard, BlueMap, dynmap, Vault]
permissions:
  landclaim.*:
    description: All landclaim permissions
    children:
      landclaim.claim: true
      landclaim.admin: true
      landclaim.list: true
  landclaim.claim:
    description: Basic claiming permission
    default: true
  landclaim.admin:
    description: Bypass protection and limits
    default: op
  landclaim.limit.*:
    description: All claim limit permissions
    default: false
  landclaim.auto:
    description: Use auto-claim feature
    default: true
  landclaim.list:
    description: List all your claims
    default: true
  landclaim.warps.limit.*:
    description: Max warps a player can set
    default: false
  landclaim.createrole.*:
    description: Max custom roles a player can create
    default: false