name: LandClaimPlugin
version: '1.8'
main: org.ayosynk.landClaimPlugin.LandClaimPlugin
api-version: '1.21'
author: AyoSynk
soft-depend: [WorldGuard]
commands:
  claim:
    description: Main land claim command
    usage: /claim [auto|trust <player>|untrust <player>|unstuck|visible [always|off]|help|reload|admin|trustlist|info]
  unclaim:
    description: Unclaim land chunks
    usage: /unclaim [auto|all [confirm]]
  unclaimall:
    description: Unclaims all your land
    usage: /unclaimall [confirm]
  c:
    description: Alias for /claim
    usage: /c
    aliases: []
  uc:
    description: Alias for /unclaim
    usage: /uc
    aliases: []
permissions:
  landclaim.*:
    description: All landclaim permissions
    children:
      landclaim.claim: true
      landclaim.admin: true
  landclaim.claim:
    description: Basic claiming permission
    default: true
  landclaim.admin:
    description: Bypass protection and limits
    default: op
  landclaim.limit.*:
    description: All claim limit permissions
    default: false
  landclaim.auto:
    description: Use auto-claim feature
    default: true